// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMcpServer(arg1) {
  return window['go']['main']['App']['AddMcpServer'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetWorkspaceFiles(arg1) {
  return window['go']['main']['App']['GetWorkspaceFiles'](arg1);
}

export function ListMcpServers() {
  return window['go']['main']['App']['ListMcpServers']();
}

export function RemoveMcpServer(arg1) {
  return window['go']['main']['App']['RemoveMcpServer'](arg1);
}

export function RunAgent(arg1, arg2) {
  return window['go']['main']['App']['RunAgent'](arg1, arg2);
}

export function SelectWorkspace() {
  return window['go']['main']['App']['SelectWorkspace']();
}

export function SetProvider(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetProvider'](arg1, arg2, arg3);
}
