// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';
import {models} from '../models';

export function AddMcpServer(arg1:config.MCPConfig):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetWorkspaceFiles(arg1:string):Promise<Array<main.FileEntry>>;

export function ListMcpServers():Promise<Array<config.MCPConfig>>;

export function RemoveMcpServer(arg1:string):Promise<void>;

export function RunAgent(arg1:string,arg2:string):Promise<string>;

export function SelectWorkspace():Promise<models.Workspace>;

export function SetProvider(arg1:string,arg2:string,arg3:string):Promise<void>;
